version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend