FROM node:16 as build

WORKDIR /app

COPY package*.json ./

RUN npm rebuild bcrypt --build-from-source

RUN npm install

COPY . ./

RUN npm run build

FROM node:18

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules

EXPOSE 8000

CMD ["node", "dist/main.js"]